spring:
  application:
    name: car-web

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/car_db?currentSchema=cars}
    username: ${DB_USER:carweb}
    password: ${DB_PASSWORD:car_password}
    driverClassName: org.postgresql.Driver

  data:
    rest:
      base-path: /api