spring:
  application:
    name: car-web

  datasource:
    url: jdbc:h2:mem:cardb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: false
